# Generated by Django 6.1 on 2026-08-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_name', models.CharField(choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว')], default='นาย', max_length=10)),
                ('stu_id', models.CharField(max_length=10, unique=True)),
                ('fname', models.CharField(blank=True, max_length=50)),
                ('lname', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
